### ISSUE TITLE
correct export to include DOI if no volume and page exists

### ISSUE THREAD

**Issue by ehenneken** [adsabs/export_service#148]
Correct export to include DOI if no volume and page exists at least for all TeX formats (AAS, MNRAS, Icar, etc). Example: MNRAS records with tmp bibcode. Example: currently we get for a record like `2019MNRAS.tmpL.175B` the following
```
\bibitem[\protect\citeauthoryear{Balashev \& Kosenko}{2019}]{2019MNRAS.tmpL.175B} Balashev S.~A., Kosenko D.~N., 2019, MNRAS.tmp, L175
```
which is meaningless. I have created an issue for the ADSImportPipeline to not generate an `eid` field for these records. This is what Classic does: http://classic.adsabs.harvard.edu/cgi-bin/abs_connect?bibcode=2019MNRAS.tmpL.175B&data_type=MNRAS (which isn't ideal either).

**Comment by golnazads** [comment]
implemented in v2.0.65.
