### ISSUE TITLE
Update help file with new custom format specification.

### ISSUE THREAD

**Issue by golnazads** [adsabs/export_service#21]

**Comment by golnazads** [comment]
Sorry could not find the message where you told me where the help files for BBB that should be updated for new custom format.

**Comment by aaccomazzi** [comment]
Help pages are in this repo: https://github.com/adsabs/adsabs.github.io/
You may want to discuss how to structure the information with @kelockhart

**Comment by golnazads** [comment]
Classics' Custom Format help file: http://adsabs.harvard.edu/abs_doc/help_pages/customformat.html#The_ADS_Custom_Format

**Comment by golnazads** [comment]
Have it in google doc here: https://docs.google.com/document/d/1ahgfwizCGGLzkKpVBWW0Rh9q9hoPc_nUYDYtqmG1_3Y/edit#heading=h.gjdgxs

**Comment by golnazads** [comment]
Submitted to @donnat and @kelockhart for review and comments.
