### ISSUE TITLE
BibTeX pubtype update for "dataset" and "software"

### ISSUE THREAD

**Issue by ehenneken** [adsabs/export_service#244]
- For `software` records, the BibTeX type should be `@software`
- For `dataset` records, the BibTeX type should be `@dataset`

For example, for `2022zndo...4482209Q` the BibTeX output should become
`
@software{2022zndo...4482209Q,
       author = {{Quinn}, Jacob and {Bouchet-Valat}, Milan and {Robinson}, Nick and {Kami{\'n}ski}, Bogumi{\l} and {Newman}, Gem and {Stukalov}, Alexey and {Vogt}, Curtis and {cjprybol} and {Holy}, Tim and {Noack}, Andreas and {Zoubritzky}, Lionel and {Kelman}, Tony and {Davies}, Eric and {ExpandingMan} and {Ian} and {Hafner}, Lilith Orion and {Piibeleht}, Morten and {Finnegan}, Rory and {evalparse} and {musvaage} and {Silberstein}, Aaron Michael and {Heimerson}, Albin and {Anthony Blaom}, PhD and {Lungwitz}, Benjamin and {K{\"o}nig}, Bernhard and {de Graaf}, Chris and {Woodfield}, Corey and {Barton}, David and {Aluthge}, Dilum and {Saba}, Elliot},
        title = "{JuliaData/CSV.jl: v0.10.12}",
         year = 2024,
        month = jan,
          eid = {10.5281/zenodo.4482209},
          doi = {10.5281/zenodo.4482209},
      version = {v0.10.12},
    publisher = {Zenodo},
       adsurl = {https://ui.adsabs.harvard.edu/abs/2022zndo...4482209Q},
      adsnote = {Provided by the SAO/NASA Astrophysics Data System}
}
`

**Comment by golnazads** [comment]
From Edwin: Good morning Golnaz: the first issue I created for the export_pipeline comes down to the following: treat the new doctype dataset in exactly the same way as software for all the export formats.
The second issue only relates to the BibTeX export format: for doctype software the BibTeX type should become @software and for the doctype dataset the BibTeX type should become @dataset (edited)

**Comment by golnazads** [comment]
@ehenneken 
The field for @dataset is the same as the @software?

**Comment by golnazads** [comment]
@ehenneken, here are there examples, @software, @misc, and @dataset. Let me know if they are correct.

@software{2023zndo...8083529K,
       author = {{Karras}, Oliver},
        title = "{Analysis of the State and Evolution of Empirical Research in Requirements Engineering}",
         year = 2023,
        month = jun,
          eid = {10.5281/zenodo.8083529},
          doi = {10.5281/zenodo.8083529},
      version = {v1.0},
    publisher = {Zenodo},
       adsurl = {https://ui.adsabs.harvard.edu/abs/2023zndo...8083529K},
      adsnote = {Provided by the SAO/NASA Astrophysics Data System}
}

@MISC{2023BoSAB..34......,
        title = "{Proceedings da XLV Reuni{\~a}o Anual da SAB}",
 howpublished = {Boletim da Sociedade Astr{\^o}nomica Brasileira. Proceedings da XLV Reuni{\~a}o Anual da SAB},
         year = 2023,
        month = jan,
       adsurl = {https://ui.adsabs.harvard.edu/abs/2023BoSAB..34......},
      adsnote = {Provided by the SAO/NASA Astrophysics Data System}
}

@dataset{2012ddsw.rept.....T,
       author = {{Thornton}, P.~E. and {Thornton}, M.~M. and {Mayer}, B.~W. and {Wilhelmi}, N. and {Wei}, Y. and {Devarakonda}, R. and {Cook}, R.},
        title = "{Daymet: Daily surface weather on a 1 km grid for North America, 1980-2008}",
 howpublished = {Oak Ridge National Laboratory (ORNL) Distributed Active Archive Center for Biogeochemical Dynamics (DAAC)},
         year = 2012,
        month = apr,
          doi = {10.3334/ORNLDAAC/1219},
       adsurl = {https://ui.adsabs.harvard.edu/abs/2012ddsw.rept.....T},
      adsnote = {Provided by the SAO/NASA Astrophysics Data System}
}

**Comment by golnazads** [comment]
@ehenneken implemented in v3.0.30

**Comment by ehenneken** [comment]
@golnazads the examples look good to me
