### ISSUE TITLE
Include volume and page for type `article-journal` (doctype: abstract) in cls formats

### ISSUE THREAD

**Issue by golnazads** [adsabs/export_service#250]
Here are the cls format and the volume/page displayed only for certain types

https://github.com/adsabs/export_service/blob/master/exportsrv/cslstyles/aasj.csl#L62
https://github.com/adsabs/export_service/blob/master/exportsrv/cslstyles/aastex.csl#L55
https://github.com/adsabs/export_service/blob/master/exportsrv/cslstyles/apsj.csl#L68
https://github.com/adsabs/export_service/blob/master/exportsrv/cslstyles/aspc.csl#L68
https://github.com/adsabs/export_service/blob/master/exportsrv/cslstyles/icarus.csl#L59
https://github.com/adsabs/export_service/blob/master/exportsrv/cslstyles/mnras.csl#L40
https://github.com/adsabs/export_service/blob/master/exportsrv/cslstyles/soph.csl#L51

@aaccomazzi do you want the format to be different for abstract volume, ie, have a `#` sign beside it for example?

**Comment by aaccomazzi** [comment]
No, just the volume number please.
