### ISSUE TITLE
Better bibtex output for conf. series

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/export_service#45]
As pointed out in this thread: https://github.com/AASJournals/AASTeX60/pull/70#issuecomment-390441709
we are not doing a great job at creating output for conference series.  The two main issues appear to be:

1. No "series" field is created (this may require a new SOLR field)
2. The "booktitle" field seems to be taken from pub_raw

Both of these may be issues with the metadata generation in adspy.  Examples:
http://adsabs.harvard.edu/cgi-bin/nph-bib_query?bibcode=2016SPIE.9911E..18A&data_type=BIBTEX
http://adsabs.harvard.edu/cgi-bin/nph-bib_query?bibcode=2013ASPC..475..383A&data_type=BIBTEX

**Comment by golnazads** [comment]
Editor and series have been added to adspy. 
Booktitle is fixed.

**Comment by golnazads** [comment]
Also make sure editor is added in.

**Comment by golnazads** [comment]
added editor and series to bibtex format. as soon as solr has the data it should get populated in the export format.

**Comment by golnazads** [comment]
implemented in v2.0.29
